### ISSUE TITLE
Create an empty example test as an incremental improvement to getting faster onboarding time

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis-libs#93]
An empty example test would take in no docker images, and would have nil/true/empty values for every interface. It would also have comments describing what to do to fill in each interface method.

Bootstrap users would be able to simply follow the empty test case, reducing copy-paste on their first attempt to create a test with a service

**Comment by mieubrisse** [comment]
I'm not sure if we actually want to do this - the cost of maintaining yet another testsuite doesn't seem worth the gain when we could be doing https://github.com/kurtosis-tech/kurtosis/issues/60 instead
