### ISSUE TITLE
Add logging to indicate changes made to set of docker images that Kurtosis is aware of

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis-libs#94]
This aids onboarding, as people want to make sure changes they make incrementally are actually picked up correctly by Kurtosis. Essentially, this looks like logging the custom params json (whats in there?) so they know kurtosis saw it

**Comment by leoporoli** [comment]
This issue was fixed on this PR:
https://github.com/kurtosis-tech/kurtosis-core/pull/253
So I will close this issue.
